---
version: 2.1

jobs:
  build:
    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2204
      image: ubuntu-2204:2022.10.2
    steps:
    - checkout
    - restore_cache:
        keys:
        - my_cache
    - run:
        name: Get test data
        command: |
          wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/utils/get_data_from_osf.sh
          bash get_data_from_osf.sh hcp_example_bids_v3
    - run:
        name: Build Docker image
        command: |
          wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/circleci/build_docker.sh
          bash build_docker.sh
    - save_cache:
        key: my_cache
        paths:
        - ~/docker
        - ~/data
        - ~/data
    - persist_to_workspace:
        root: /home/circleci
        paths:
        - data/hcp_example_bids_v3
        - docker/image.tar

  test:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run: docker load -i /tmp/workspace/docker/image.tar
    - run: mkdir -p ${HOME}/outputs
    - run:
        name: print version
        command: |
          docker run -ti --rm --read-only \
            -v /tmp/workspace/data/hcp_example_bids_v3:/bids_dataset \
              bids/${CIRCLE_PROJECT_REPONAME,,} --version
    - run:
        name: participant level tests for single session dataset
        command: |
          docker run -ti --rm --read-only \
            -v /tmp/workspace/data/hcp_example_bids_v3:/bids_dataset \
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                /bids_dataset \
                /outputs \
                participant --participant_label 100307 \
                --stages PreFreeSurfer \
                --license_key="*CxjskRdd7" \
                --n_cpus 2
        no_output_timeout: 6h

  deploy:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run: docker load -i /tmp/workspace/docker/image.tar
    - run:
        name: push to dockerhub
        command: |
          wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/circleci/push_docker.sh
          bash push_docker.sh

  test_latest:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
    - run:
        name: Get test data
        command: |
          wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/utils/get_data_from_osf.sh
          bash get_data_from_osf.sh hcp_example_bids_v3
    - run:
        name: Pull image
        command: docker pull bids/${CIRCLE_PROJECT_REPONAME,,}
    - run:
        name: participant level tests for single session dataset
        command: |
          docker run -ti --rm --read-only \
            -v ~/data/hcp_example_bids_v3:/bids_dataset \
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                /bids_dataset \
                /outputs \
                participant --participant_label 100307 \
                --stages PreFreeSurfer \
                --processing_mode legacy \
                --license_key="*CxjskRdd7" \
                --n_cpus 2

workflows:
  build-test-deploy:
    jobs:
    - build
    - test_latest
    - test:
        requires:
        - build
    - deploy:
        context:
        - dockerhub
        requires:
        - test
        filters:
          tags:
            only: /.*/

# VS Code Extension Version: 1.5.1
